package com.agentcenter.bridge.domain.runtime;

public enum RuntimeEventType {
    STATUS, ASSISTANT_DELTA, SKILL_STARTED, SKILL_COMPLETED,
    MCP_CALL, PERMISSION_REQUIRED, ERROR, CONFIRMATION_CREATED,
    RESOURCE_REFRESH_STARTED, RESOURCE_REFRESH_COMPLETED, RESOURCE_REFRESH_FAILED,
    SKILL_INSTALLED, SKILL_UPDATED, SKILL_DELETED, SKILL_ENABLED, SKILL_DISABLED,
    MCP_ENABLED, MCP_DISABLED, MCP_HEALTH_CHECKED, MCP_TOOLS_REFRESHED
}
