import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const marker = "Generated by packages/agent-workflow/scripts/install.ts"
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..")
const pluginDir = path.join(repoRoot, ".opencode", "plugins")
const pluginFile = path.join(pluginDir, "agent-workflow.ts")
const force = process.argv.includes("--force")
const content = [
  "/**",
  " * Agent Workflow OpenCode plugin shim.",
  ` * ${marker}`,
  " */",
  'export { default } from "../../packages/agent-workflow/src/opencode/plugin"',
  "",
].join("\n")

await mkdir(pluginDir, { recursive: true })

const existing = await readFile(pluginFile, "utf8").catch(() => undefined)
if (existing && !existing.includes(marker) && !force) {
  console.error(`Refusing to overwrite existing plugin file: ${pluginFile}`)
  console.error("Re-run with --force if you intentionally want to replace it.")
  process.exit(1)
}

await writeFile(pluginFile, content)

console.log("Agent Workflow plugin installed.")
console.log(`Plugin shim: ${pluginFile}`)
console.log("OpenCode auto-loads .opencode/plugins/*.ts for this workspace.")
console.log("Run `bun --cwd packages/agent-workflow uninstall:opencode` to remove it.")
