import { readFile, rm } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const marker = "Generated by packages/agent-workflow/scripts/install.ts"
const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../..")
const pluginFile = path.join(repoRoot, ".opencode", "plugins", "agent-workflow.ts")
const force = process.argv.includes("--force")
const existing = await readFile(pluginFile, "utf8").catch(() => undefined)

if (!existing) {
  console.log("Agent Workflow plugin is not installed.")
  process.exit(0)
}

if (!existing.includes(marker) && !force) {
  console.error(`Refusing to remove a plugin file not created by the installer: ${pluginFile}`)
  console.error("Re-run with --force if you intentionally want to remove it.")
  process.exit(1)
}

await rm(pluginFile)
console.log("Agent Workflow plugin uninstalled.")
console.log(`Removed: ${pluginFile}`)
